FROM node:10.24.1-alpine3.11 as builder
COPY . /app
RUN npm config set -g registry https://registry.npm.taobao.org && \
    npm install gitbook-cli -g 
RUN cd /app && \
    npm install {{ range  .NpmInstallPlugins }} gitbook-plugin-{{ . }}{{ end }} && \
    gitbook install && \
    gitbook build 

FROM nginx
COPY --from=builder /app/_book /var/www
